/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.actionHandler;
import java.awt.event.ActionEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import model.header;
import model.headerTable;
import model.line;
import model.lineTable;

/**
 *
 * @author Lenovo
 */
public class myGUI extends javax.swing.JFrame {

    private actionHandler handler;
    
    private ArrayList<header> headersList;
    private ArrayList<line> linesList;
    private headerTable headerTableModel;
    private lineTable lineTableModel;
    private myGUI frame;

    /**
     * Creates new form myGUI
     */
    public myGUI() {
        handler = new actionHandler(this);
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        headersTable = new javax.swing.JTable();
        headersTable.getSelectionModel().addListSelectionListener(this.handler);
        newHeaderbtn = new javax.swing.JButton();
        newHeaderbtn.addActionListener(this.handler);
        deleteHeaderBtn = new javax.swing.JButton();
        deleteHeaderBtn.addActionListener(this.handler);
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        linesTable = new javax.swing.JTable();
        newLineBtn = new javax.swing.JButton();
        newLineBtn.addActionListener(this.handler);
        deleteLineBtn = new javax.swing.JButton();
        deleteLineBtn.addActionListener(this.handler);
        headerID = new javax.swing.JTextField();
        headerDate = new javax.swing.JTextField();
        headerCust = new javax.swing.JTextField();
        headerTotal = new javax.swing.JTextField();
        exitBtn = new javax.swing.JButton();
        exitBtn.addActionListener(this.handler);
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        saveFile = new javax.swing.JMenuItem();
        saveFile.addActionListener(this.handler);
        loadFile = new javax.swing.JMenuItem();
        loadFile.addActionListener(this.handler);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        headersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(headersTable);

        newHeaderbtn.setText("New Invoice");

        deleteHeaderBtn.setText("Delete Invoice");

        jLabel1.setText("Invoice");

        jLabel2.setText("Date");

        jLabel3.setText("Customer");

        jLabel4.setText("Total");

        linesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane2.setViewportView(linesTable);

        newLineBtn.setText("New Line");

        deleteLineBtn.setText("Delete Line");

        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        jMenu2.setText("File");

        saveFile.setText("Save File");
        jMenu2.add(saveFile);

        loadFile.setText("Load File");
        jMenu2.add(loadFile);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(newHeaderbtn)
                        .addGap(18, 18, 18)
                        .addComponent(deleteHeaderBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(headerTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(headerCust, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 216, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(headerDate, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(headerID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitBtn))))
            .addGroup(layout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addComponent(newLineBtn)
                .addGap(18, 18, 18)
                .addComponent(deleteLineBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(newHeaderbtn)
                            .addComponent(deleteHeaderBtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(headerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exitBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(headerDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(headerCust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(headerTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newLineBtn)
                    .addComponent(deleteLineBtn))
                .addContainerGap(178, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
       // this.addWindowListener(handler);
    }//GEN-LAST:event_formWindowClosing

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(myGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(myGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(myGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(myGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                myGUI frame = new myGUI();
                frame.setVisible(true);

                
             
    
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteHeaderBtn;
    private javax.swing.JButton deleteLineBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JTextField headerCust;
    private javax.swing.JTextField headerDate;
    private javax.swing.JTextField headerID;
    private javax.swing.JTextField headerTotal;
    private javax.swing.JTable headersTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable linesTable;
    private javax.swing.JMenuItem loadFile;
    private javax.swing.JButton newHeaderbtn;
    private javax.swing.JButton newLineBtn;
    private javax.swing.JMenuItem saveFile;
    // End of variables declaration//GEN-END:variables

 
    
     
    public actionHandler getHandler() {
        return handler;
    }

    public void setHandler(actionHandler handler) {
        this.handler = handler;
    }

    public ArrayList<header> getHeadersList() {
        try {
            if (headersList == null) {
                throw new Exception();
            }
        } catch (Exception exp) {
            JOptionPane.showMessageDialog(this, "No headers to select. Please load a file first", "No data", JOptionPane.CLOSED_OPTION);

        }
        return headersList;
    }

    public void setHeadersList(ArrayList<header> headersList) {
        this.headersList = headersList;
        this.headerTableModel = new headerTable(this.headersList);
        this.headerTableModel.fireTableDataChanged();
        this.headersTable.setModel(headerTableModel);
    }

    public ArrayList<line> getLinesList() {

        try {
            if (headersList == null) {
                throw new Exception();
            }
        } catch (Exception exp) {
            JOptionPane.showMessageDialog(this, "Please select a header first", "No data", JOptionPane.CLOSED_OPTION);

        }
        return linesList;
    }

    public void setLinesList(ArrayList<line> linesList) {
        this.linesList = linesList;
        this.lineTableModel = new lineTable(this.linesList);
        this.lineTableModel.fireTableDataChanged();
        this.linesTable.setModel(lineTableModel);

    }

    public JTable getHeadersTable() {
        return headersTable;
    }

    public void setHeadersTable(JTable headersTable) {
        this.headersTable = headersTable;

    }

    public JTable getLinesTable() {
        return linesTable;
    }

    public void setLinesTable(JTable linesTable) {
        this.linesTable = linesTable;
    }

    public JTextField getHeaderCust() {
        return headerCust;
    }

    public JTextField getHeaderDate() {
        return headerDate;
    }

    public JTextField getHeaderID() {
        return headerID;
    }

    public JTextField getHeaderTotal() {
        return headerTotal;
    }

    public headerTable getHeaderTableModel() {
        return headerTableModel;
    }

    public void setHeaderTableModel(headerTable headerTableModel) {
        this.headerTableModel = headerTableModel;
    }

    public lineTable getLineTableModel() {
        return lineTableModel;
    }

    public void setLineTableModel(lineTable lineTableModel) {
        this.lineTableModel = lineTableModel;
    }

}
